# Generated by Django 3.0.4 on 2020-03-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moudles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(max_length=5)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating_system.Moudles')),
                ('professer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating_system.Professors')),
            ],
        ),
        migrations.AddField(
            model_name='moudles',
            name='taughtBy',
            field=models.ManyToManyField(to='rating_system.Professors'),
        ),
    ]
