# Generated by Django 3.0.4 on 2020-03-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
