# Generated by Django 3.0.4 on 2020-03-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_system', '0003_auto_20200310_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
