# Generated by Django 3.0.4 on 2020-03-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_system', '0004_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
